[Flash]
GiantScalePercent=135
RunForce=80
TurboForce=260
ExplosiveBullets=1

UseCustomModel=0
CustomModelName=

[Traffic]
TrafficPercent=100
AddonCarModelName=ironroadster

[Chaos]
; Final "LSD" mode. Toggle in-game with F11.
Enabled=1
